on:
  workflow_dispatch:

jobs:
  build-release:
    name: Build app
    runs-on: ubuntu-latest
    env:
      androidArch: x86_64
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true

      - name: Validate gradle wrapper checksum
        uses: gradle/actions/wrapper-validation@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0

      - name: Set up JDK 21
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          cache-dependency-path: rcbridge/go.sum
          go-version-file: rcbridge/go.mod

      - name: Get NDK version
        id: get_version
        shell: bash
        run: |
          sed -nr \
              -e 's/^\s*(compileSdk)\s*(=)\s([0-9]+).*$/\1\2\3/p' \
              -e 's/^\s*(ndkVersion)\s*(=)\s"(.+)".*$/\1\2\3/p' \
              app/build.gradle.kts \
              >> "${GITHUB_OUTPUT}"

      - name: Decode Keystore
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 --decode > ${{ github.workspace }}/release-key.jks

      - name: Build Release APK
        env:
          RELEASE_KEYSTORE: ${{ github.workspace }}/release-key.jks
          RELEASE_KEYSTORE_PASSPHRASE: ${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSPHRASE: ${{ secrets.RELEASE_KEY_PASSPHRASE }}
        run: ./gradlew --no-daemon assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk
          retention-days: 7